version: '3.8'

services:
  spark-notebook:
    build: .
    environment:
      - HADOOP_HOME=/usr/local/hadoop
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
